### ISSUE TITLE
Returning an object type is not a valid return 

### ISSUE THREAD

**Issue by BenjaminLesne** [typed-rocks/type-buddy#2]
I would expect the following types.tb to be valid syntax but currently is not:
```ts
function A(T) {
  if (T extends string) {
    return {
      test: true
    };
  } else {
    return false;
  }
}
```

or return the object with parentheses:

```ts
function A(T) {
  if (T extends string) {
    return ({
      test: true
    });
  } else {
    return false;
  }
}
```

Those types trigger:

```ts
//There needs to be a EXACTLY ONE return inside of if, else if or else blocks. NOTHING else.
Line: 2
```

I'm using the [web interface](https://typed-rocks.github.io/type-buddy/):

![image](https://github.com/user-attachments/assets/42c2b0df-b375-4a65-bdba-a54f1f7f20cd)

Am I missing something?

**Comment by chwoerz** [comment]
Absolutely. This should work. I will fix it👍

**Comment by chwoerz** [comment]
@BenjaminLesne 

I am working on it but a quick workaround would be to put it on one line: 

```ts
 return {test: string};
```

**Comment by chwoerz** [comment]
@BenjaminLesne It's now fixed for the Webapp and the extension :). Let me know if it now works properly for you, then you can close the issue.
